// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notkace.Api.Data;

#nullable disable

namespace Notkace.Api.Data.Migrations
{
    [DbContext(typeof(NotkaceContext))]
    [Migration("20260820222519_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Notkace.Api.Data.Entities.Asset", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    b.Property<long>("AssetTypeId")
                        .HasColumnType("bigint")
                        .HasColumnName("ASSET_TYPE_ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("ASSET", (string)null);
                });

            modelBuilder.Entity("Notkace.Api.Data.Entities.HdPriority", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<long>("Ordinal")
                        .HasColumnType("bigint")
                        .HasColumnName("ORDINAL");

                    b.HasKey("Id");

                    b.ToTable("HD_PRIORITY", (string)null);
                });

            modelBuilder.Entity("Notkace.Api.Data.Entities.HdStatus", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<long>("Ordinal")
                        .HasColumnType("bigint")
                        .HasColumnName("ORDINAL");

                    b.HasKey("Id");

                    b.ToTable("HD_STATUS", (string)null);
                });

            modelBuilder.Entity("Notkace.Api.Data.Entities.HdTicket", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    b.Property<long?>("AssetId")
                        .HasColumnType("bigint")
                        .HasColumnName("ASSET_ID");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED");

                    b.Property<string>("CustomFieldValue1")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CUSTOM_FIELD_VALUE1");

                    b.Property<string>("CustomFieldValue2")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CUSTOM_FIELD_VALUE2");

                    b.Property<string>("CustomFieldValue5")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CUSTOM_FIELD_VALUE5");

                    b.Property<long?>("HdPriorityId")
                        .HasColumnType("bigint")
                        .HasColumnName("HD_PRIORITY_ID");

                    b.Property<long>("HdQueueId")
                        .HasColumnType("bigint")
                        .HasColumnName("HD_QUEUE_ID");

                    b.Property<long?>("HdStatusId")
                        .HasColumnType("bigint")
                        .HasColumnName("HD_STATUS_ID");

                    b.Property<long?>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("OWNER_ID");

                    b.Property<long?>("SubmitterId")
                        .HasColumnType("bigint")
                        .HasColumnName("SUBMITTER_ID");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SUMMARY");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TITLE");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("HdPriorityId");

                    b.HasIndex("HdQueueId");

                    b.HasIndex("HdStatusId");

                    b.HasIndex("SubmitterId");

                    b.HasIndex("OwnerId", "HdStatusId");

                    b.ToTable("HD_TICKET", (string)null);
                });

            modelBuilder.Entity("Notkace.Api.Data.Entities.HdTicketChange", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COMMENT");

                    b.Property<long>("HdTicketId")
                        .HasColumnType("bigint")
                        .HasColumnName("HD_TICKET_ID");

                    b.Property<bool>("OwnersOnly")
                        .HasColumnType("bit")
                        .HasColumnName("OWNERS_ONLY");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("TIMESTAMP");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("HdTicketId");

                    b.HasIndex("UserId");

                    b.ToTable("HD_TICKET_CHANGE", (string)null);
                });

            modelBuilder.Entity("Notkace.Api.Data.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FULL_NAME");

                    b.Property<long?>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("ROLE_ID");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("Id");

                    b.ToTable("USER", (string)null);
                });

            modelBuilder.Entity("Notkace.Api.Data.Entities.HdTicket", b =>
                {
                    b.HasOne("Notkace.Api.Data.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId");

                    b.HasOne("Notkace.Api.Data.Entities.HdPriority", "HdPriority")
                        .WithMany()
                        .HasForeignKey("HdPriorityId");

                    b.HasOne("Notkace.Api.Data.Entities.HdStatus", "HdStatus")
                        .WithMany()
                        .HasForeignKey("HdStatusId");

                    b.HasOne("Notkace.Api.Data.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId");

                    b.HasOne("Notkace.Api.Data.Entities.User", "Submitter")
                        .WithMany()
                        .HasForeignKey("SubmitterId");

                    b.Navigation("Asset");

                    b.Navigation("HdPriority");

                    b.Navigation("HdStatus");

                    b.Navigation("Owner");

                    b.Navigation("Submitter");
                });

            modelBuilder.Entity("Notkace.Api.Data.Entities.HdTicketChange", b =>
                {
                    b.HasOne("Notkace.Api.Data.Entities.HdTicket", "HdTicket")
                        .WithMany()
                        .HasForeignKey("HdTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Notkace.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("HdTicket");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
