<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>72503c82-3e9f-40bc-9fae-c850c4ca444a</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FastEndpoints" Version="8.3.0" />
      <PackageReference Include="FastEndpoints.Generator" Version="8.3.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
      <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.11" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

</Project>
