name: Deploy .NET 9 API (Direct to Droplet)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish API
        run: dotnet publish -c Release -o out

      - name: Build Docker image
        run: docker build -t api.archerharmony.com:latest .

      - name: Save Docker image as tarball
        run: |
          docker save api.archerharmony.com:latest -o api.tar
          chmod +r api.tar

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "api.tar"
          target: "${{ secrets.PROJECT_PATH }}"
      
      - name: SSH and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            docker load -i api.tar
            docker compose up -d api
            docker image prune -f
            rm api.tar
